name: Run build and test
on:
  pull_request:
    branches:
      - main
jobs:
  build_and_test:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "12.5.1"
      - name: Install xcpretty
        run: gem install xcpretty
      - name: Build and test
        run: xcodebuild -scheme GitHubClient clean build test -destination "name=iPhone 12" -enableCodeCoverage YES | xcpretty
      - uses: codecov/codecov-action@v2
